add prerender export to layout
The default option in svelte configuration is deprecated and will be
removed eventually.

Error: config.kit.prerender.default has been removed. You can set it inside the top level +layout.js instead. See the PR for more information: sveltejs/kit#6197